version: "3"
services:
  consumer:
    image: actor-image
    ports:
      - "8080:8080"
    networks:
      - consumer-producer
    depends_on:
      - producer

  producer:
    image: movie-image
    ports:
      - "8081:8081"
    networks:
      - consumer-producer

networks:
  consumer-producer: